### ISSUE TITLE
Create 2 Prototype Themes

### ISSUE THREAD

**Issue by ProRichyMan** [Reinhardtlotter/flask_portfolio#11]
- [x] lay out prototype/drawing theme pages
- [x] Research tags to integrate the colors
- [x] Finalized and put colors into code/ website
- [x] Research tags to integrate the fonts
- [x] Finalized and put fonts into code/ website
- [x] Research tags to integratre the backgrounds
- [x] Finalized and put new backgrounds into code/ website

**Comment by Pitsco** [comment]
https://www.w3schools.com/w3css/defaulT.asp 

for any helpful tips
