### ISSUE TITLE
Peer Review Week 4

### ISSUE THREAD

**Issue by ProRichyMan** [Reinhardtlotter/flask_portfolio#25]

**Comment by xu-ellen** [comment]
Team Planning. Scrum board tasks made sense and contained links/tangibles for evidence, nice format with the checklists and each person completing their tasks. Could show more planning in todo and in progress to show what you are planning to do next week. 0.9/1

**Comment by xu-ellen** [comment]
Team work. Good cohesion in video with each person working on something and contributing to the project. Besides the minilabs, it was hard to tell what the main vision of the website is and how the individual pages fit together. Great main page and About us page! Only suggestion would be to work more on components to your website outside of what was assigned in class to make it clearer what the overall function of the site is. 1.75/2

**Comment by tangalice** [comment]
Individual Technicals. Individual review in the video is strong, everyone worked on something technical. Individual commits also reflect this. However there are no issues opened in the todo section of the scrum board, issues need to be opened and assigned to show that you have plans for the upcoming week. 1.9/2

**Comment by tangalice** [comment]
Score is 4.45 for everyone.
