### ISSUE TITLE
Video Notes

### ISSUE THREAD

**Issue by Reinhardtlotter** [Reinhardtlotter/flask_portfolio#3]
[Unit 1.2](https://apclassroom.collegeboard.org/103/home?apd=0gaql55tbj)
[Unit 1.4](https://apclassroom.collegeboard.org/103/home?apd=a21dvlri4q)

- [x] Video 1 finished
- [x] Video 2 finished

**Comment by Reinhardtlotter** [comment]
- [ ] Video 1
- [ ] Video 2

**Comment by BrianZhang2016** [comment]
[Please Check](https://docs.google.com/document/d/1GzQr01ImIy1J9VgEolsr705FJK2q-AatR-O4lZCbIw4/edit?usp=sharing)
