### ISSUE TITLE
Week 8 Reviews

### ISSUE THREAD

**Issue by ProRichyMan** [Reinhardtlotter/flask_portfolio#66]
Score: 4.5/5 for presentations
TPT: 3/3 from Anthony

**Nathan**: 7.5/8
**Brian**: 7.5/8
**Reinhardt**: 7.5/8
**Derrick**: 7.5/8

**Comment by DerekBokelman** [comment]
Positives: 
I like the hovering over the valorant agents and giving a description of them.
I like the clip of the day page.
I love the feature where you can see all of the game maps.

Things to work on: 
I think you can make the background a bit of a softer color to make the website a little more friendly to the eye

**Comment by willcyber** [comment]
I think the like button is a cool feature. However, I think it's strange that you can give more than one like. I think likes would be kind of pointless if one person could give a video a thousand likes. I really like the layout of the website. It fits perfectly with a website on Valorant.

**Comment by katiehickman** [comment]
I liked the hover feature on your game characters and how it related to the binary. I also liked the extension of the navbar and maybe you could change the color of your navbar.

**Comment by isabelle926** [comment]
I like the map page and the hover feature.

**Comment by xXAASXx** [comment]
Things I liked:
I do not play Valorant but I like the website idea and the design of what you guys are working on.
I like how much you guys have implemented hovering over images to show what they are.

Things that can be improved:
I think you can make the background a bit of a softer color to make the website a little more friendly to the eye.

**Comment by kar722** [comment]
The hovering effects for each agent was very cool. I also liked how implemented the amount of likes. One suggestion I would give is to make the backgrounds more colorful as they were plain.

**Comment by tonyhieu** [comment]
I like the features of hovering over the agents and getting a small bio about them. One thing I'd add is more interactivity; it seems like there isn't a lot that the users can do.

**Comment by danaylevy2004** [comment]
Things I Liked:
- I really liked the Valorant-themed website that displays gaming clips and the idea itself is unique. All of the code seems to be managed in an organized manner and is easy to follow. I liked the incorporation of the theme with the video game theming. 

Things to Improve On: 
- Maybe incorporate more of the minilabs in the website. One example of this is to maybe incorporate API into displaying shots or clips.

**Comment by tangalice** [comment]
I like how when you hover your mouse over the map there is a pop up. An improvement would be to add more visuals so your website isn't as empty.

**Comment by VidhiKulkarni** [comment]
I like the hovering feature. The graphics look good. I also like the idea of incorporating the API. One thing to improve on would be the layout.
